// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mikes_grpc_demo.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mikesgrpcdemo {

  /// <summary>Holder for reflection information generated from mikes_grpc_demo.proto</summary>
  public static partial class MikesGrpcDemoReflection {

    #region Descriptor
    /// <summary>File descriptor for mikes_grpc_demo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MikesGrpcDemoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVtaWtlc19ncnBjX2RlbW8ucHJvdG8SDW1pa2VzZ3JwY2RlbW8iFAoETmFt",
            "ZRIMCgRuYW1lGAEgASgJIjwKC0NvbnRhY3RJbmZvEgwKBG5hbWUYASABKAkS",
            "DQoFZW1haWwYAiABKAkSEAoIcGhvbmVOdW0YAyABKAkiHwoOR3JvY2VyeVJl",
            "cXVlc3QSDQoFaXRlbXMYASABKAUiIgoPR3JvY2VyeVJlc3BvbnNlEg8KB2dy",
            "b2NlcnkYASABKAkypwEKDU1pa2VzR3JwY0RlbW8SQwoOR2V0Q29udGFjdElu",
            "Zm8SEy5taWtlc2dycGNkZW1vLk5hbWUaGi5taWtlc2dycGNkZW1vLkNvbnRh",
            "Y3RJbmZvIgASUQoMR2V0R3JvY2VyaWVzEh0ubWlrZXNncnBjZGVtby5Hcm9j",
            "ZXJ5UmVxdWVzdBoeLm1pa2VzZ3JwY2RlbW8uR3JvY2VyeVJlc3BvbnNlIgAw",
            "AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mikesgrpcdemo.Name), global::Mikesgrpcdemo.Name.Parser, new[]{ "Name_" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mikesgrpcdemo.ContactInfo), global::Mikesgrpcdemo.ContactInfo.Parser, new[]{ "Name", "Email", "PhoneNum" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mikesgrpcdemo.GroceryRequest), global::Mikesgrpcdemo.GroceryRequest.Parser, new[]{ "Items" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mikesgrpcdemo.GroceryResponse), global::Mikesgrpcdemo.GroceryResponse.Parser, new[]{ "Grocery" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Name : pb::IMessage<Name> {
    private static readonly pb::MessageParser<Name> _parser = new pb::MessageParser<Name>(() => new Name());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Name> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mikesgrpcdemo.MikesGrpcDemoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Name() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Name(Name other) : this() {
      name_ = other.name_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Name Clone() {
      return new Name(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int Name_FieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name_ {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Name);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Name other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name_ != other.Name_) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name_.Length != 0) hash ^= Name_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name_.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name_);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name_.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name_);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Name other) {
      if (other == null) {
        return;
      }
      if (other.Name_.Length != 0) {
        Name_ = other.Name_;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Name_ = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ContactInfo : pb::IMessage<ContactInfo> {
    private static readonly pb::MessageParser<ContactInfo> _parser = new pb::MessageParser<ContactInfo>(() => new ContactInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ContactInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mikesgrpcdemo.MikesGrpcDemoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContactInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContactInfo(ContactInfo other) : this() {
      name_ = other.name_;
      email_ = other.email_;
      phoneNum_ = other.phoneNum_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContactInfo Clone() {
      return new ContactInfo(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 2;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phoneNum" field.</summary>
    public const int PhoneNumFieldNumber = 3;
    private string phoneNum_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PhoneNum {
      get { return phoneNum_; }
      set {
        phoneNum_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ContactInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ContactInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Email != other.Email) return false;
      if (PhoneNum != other.PhoneNum) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (PhoneNum.Length != 0) hash ^= PhoneNum.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Email);
      }
      if (PhoneNum.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PhoneNum);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (PhoneNum.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PhoneNum);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ContactInfo other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.PhoneNum.Length != 0) {
        PhoneNum = other.PhoneNum;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Email = input.ReadString();
            break;
          }
          case 26: {
            PhoneNum = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GroceryRequest : pb::IMessage<GroceryRequest> {
    private static readonly pb::MessageParser<GroceryRequest> _parser = new pb::MessageParser<GroceryRequest>(() => new GroceryRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GroceryRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mikesgrpcdemo.MikesGrpcDemoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroceryRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroceryRequest(GroceryRequest other) : this() {
      items_ = other.items_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroceryRequest Clone() {
      return new GroceryRequest(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private int items_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Items {
      get { return items_; }
      set {
        items_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GroceryRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GroceryRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Items != other.Items) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Items != 0) hash ^= Items.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Items != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Items);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Items != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Items);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GroceryRequest other) {
      if (other == null) {
        return;
      }
      if (other.Items != 0) {
        Items = other.Items;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Items = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GroceryResponse : pb::IMessage<GroceryResponse> {
    private static readonly pb::MessageParser<GroceryResponse> _parser = new pb::MessageParser<GroceryResponse>(() => new GroceryResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GroceryResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mikesgrpcdemo.MikesGrpcDemoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroceryResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroceryResponse(GroceryResponse other) : this() {
      grocery_ = other.grocery_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroceryResponse Clone() {
      return new GroceryResponse(this);
    }

    /// <summary>Field number for the "grocery" field.</summary>
    public const int GroceryFieldNumber = 1;
    private string grocery_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Grocery {
      get { return grocery_; }
      set {
        grocery_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GroceryResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GroceryResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Grocery != other.Grocery) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Grocery.Length != 0) hash ^= Grocery.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Grocery.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Grocery);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Grocery.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Grocery);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GroceryResponse other) {
      if (other == null) {
        return;
      }
      if (other.Grocery.Length != 0) {
        Grocery = other.Grocery;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Grocery = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
